// export const NAME = 'value';
export const CHANGE_FILTER = 'CHANGE_FILTER';
export const CHANGE_PAGE_NUMBER = 'CHANGE_PAGE_NUMBER';
export const SELECT_SHOW_ROWS = 'SELECT_SHOW_ROWS';
export const CHANGE_NEXT_PAGE = 'CHANGE_NEXT_PAGE';
export const CHANGE_PREVIOUS_PAGE = 'CHANGE_PREVIOUS_PAGE';
export const SORT_ROWS = 'SORT_ROWS';
export const CHANGE_FILTER_NO_MATCHING = 'CHANGE_FILTER_NO_MATCHING';
export const SELECT_START_DATE = 'SELECT_START_DATE';
export const SELECT_END_DATE = 'SELECT_END_DATE';
export const RESET_STATE = 'RESET_STATE';

//fetch
export const LOAD_DATA_ATTEMPTED = 'LOAD_DATA_ATTEMPTED';
export const LOAD_DATA_SUCCEEDED = 'LOAD_DATA_SUCCEEDED';
export const LOAD_DATA_FAILED = 'LOAD_DATA_FAILED';


//stats
export const LOAD_TOTAL_SALES = 'LOAD_TOTAL_SALES';
